README.md

1. Without `-print0` it was throwing the ` xargs: insufficient space for argument`
2. Ignoring `node_modules` folder... :wink:

Better find + xargs command

---

index.js

Your `package.json` describes `"main": "index.js"` but `index.js` file didn't exist.
This allows us to require and use xto6 in Node.js.

add main file

---

src/transformation/let.js
test/transformation/let.js

currently `var i = 0; i++;` is transformed to `const i = 0; i++;` but `let` should be used in this case, so I fixed it.

consider update_expression to determine let/const

---

package.json
src/transformer.js
src/utils/ast-generator.js

Related to #32 .
I'm working on transforming our ES5 code to ES2015, typically `var` to `let` and `const`. We want to maintain the whole structure of our code except those changes, so `benjamn/recast` is better for our use.
So I tried to replace `acorn`, `escodegen` to `recast` and it worked fine in local.
This is only a proposal so I've not fixed test code yet, but I'd like to do it if you want to merge this.
Thanks.

Proposal: use `benjamn/recast` instead of `acorn` and `escodegen`

---

bin/file.js
bin/index.js
src/transformer.js
test/transformation/comments.js

Current lebab only allows you to run all the available transforms. There's special-case option for disabling classes transform, but besides this you're forced to do all transforms.
But I'd like to pick some particular transform and run my code only through that. I can then migrate my codebase one transform at a time. When something goes wrong, I'll know the specific transform that is to be blamed.
So I added `--transformers` option which allows one to enable just one particular transform or several of them. When used, all other transforms that aren't specified will be disabled.
The first commit contains the core of this change. The other commits are just a bit of cleanup to simplify the whole transformers configuration pipeline.
Questions to consider before merging:
- What's the best name …

Add command line option for doing only specific transforms

---

src/transformation/let.js
test/transformation/let.js

A simple fix - just check for the correct type.
Fixes #53

Fix for member-assignment causing let to be used instead of const

---

bin/file.js
src/transformation/object-shorthands.js
src/transformer.js
test/transformation/object-shorthands.js

Converts `{foo: foo}` to `{foo}`.
Simple as that.

Implement object-shorthands transformation

---

src/syntax/arrow-function-expression.js
src/syntax/block-statement.js
src/syntax/function-expression.js
src/transformation/arrow-functions.js
test/transformation/arrow-functions.js

Fixes issues #50, #51 and #52. Properly handling the presence of `this` and `arguments`, and targeting all function expressions.
Additionally:
- convert function expressions with single return statement to short form.
- don't convert named function expressions.
- don't convert generators.
In the end also refactored the arrow-function transform and syntax node code a bit.

Various improvements to arrow-function transform

---

bin/file.js
src/transformation/no-strict.js
src/transformer.js
test/transformation/no-strict.js

ES6-specific code runs in strict mode and Babel also adds "use strict"
automatically to the generated code.  So there's rarely any need to
manually add a "use strict" directive.
This transform is also present in 5to6-codemod, which gave me the idea
of implementing it also in lebab:
- https://github.com/5to6/5to6-codemod

Implement "use strict" removal

---

bin/file.js
bin/index.js
src/syntax/export-default-declaration.js
src/syntax/import-declaration.js
src/syntax/import-default-specifier.js
src/syntax/variable-declaration.js
src/transformation/export-commonjs.js
src/transformation/import-commonjs.js
src/transformer.js
test/transformation/export-commonjs.js
test/transformation/import-commonjs.js

Support default import and export.
Not enabling this by default but instead it needs to be explicitly enabled through `--module commonjs` switch.
There are still some deficiencies in this implementation resulting from the fact that import declarations work like `const` declaration not like `var`. This means:
- they can't be re-assigned.
- they can't be referenced before being declared.
These things are currently not checked for. Those checks however are very similar to what we want to do for `let/const` transform. Maybe we could re-purpose the logic for let/const (when it gets fixed) to also cover the import case. Alternatively we could first perform transform to `let/const` and then only transform `const` declarations to imports.
This should mostly solve #12

Transform for CommonJS module definitions

---

src/transformation/let.js
src/utils/type-checker.js
test/transformation/let.js

Complete rewrite of let transform:
- Broke it all up to several smaller functions.
- Instead of single variables lookup table
using an array (functionScopeStack) of lookup tables
which are added/removed on entering/leaving a function.
- Used const for all variables instead of let.
- Added isES6Function() type-checker helper.
Fixes #75 
Note: This doesn't really solve all the problems with let transform. A major change is needed to properly account for variable hoisting and block scoping. But hopefully at least a change in the right direction.

Track variable scope for when choosing let v/s const

---

src/scope/block-scope.js
src/scope/function-hoister.js
src/scope/function-scope.js
src/scope/scope-manager.js
src/scope/scope.js
src/scope/variable-group.js
src/scope/variable-marker.js
src/scope/variable.js
src/transformation/import-commonjs.js
src/transformation/let.js
src/utils/function-type.js
src/utils/multi-replace-statement.js
src/utils/type-checker.js
src/utils/variable-type.js
test/transformation/let.js

Took a while, but here it finally is.
Rewrote the whole let-transform to correctly handle JavaScript variable scoping.
- No more transforms `var` declarations that aren't properly block-scoped. Fixes #76 
- Splits multi-variable declarations up to multiple declarations when some can be converted to `const` and some to `let`.
- Considers function names and parameters also as variables, ignoring `var` declarations that re-declare them.
- Handles arrow-functions.
The resulting code is way larger than the old version, split over several files. Most of the new stuff is in new `scope/` dir. There are also some new utilities in `utils/` dir. The diff of `let-transform.js` is not really worth reading - it's a complete rewrite, so the similarities are more of an accidental kind.
Also added loads …

Proper function- and block-scoping support for let-transform

---

bin/index.js
src/transformer.js
test/transformation/arrow-functions.js
test/transformation/classes.js
test/transformation/comments.js
test/transformation/default-arguments.js
test/transformation/export-commonjs.js
test/transformation/import-commonjs.js
test/transformation/let.js
test/transformation/no-strict.js
test/transformation/object-methods.js
test/transformation/object-shorthands.js
test/transformation/template-string.js

A bit of cleanup to change the Transformer class that has loads of methods into much simpler version that has just a single method which just takes in ES5 code and outputs ES6 code.
As a result reducing the amount of code in all places that use the Transformer, especially in tests.

Simpler Transformer class

---

src/transformer.js
test/transformation/comments.js

Strip the hash-bang comment before doing the actual parsing,
then add it back afterwards.
Added jshint ignore:line comment, as jshint otherwise reports
the `all` variable as unused.  But using the destrucor makes
reading the regex match so much simpler.
Fixes #55

Ignore #!/usr/bin/env node comment at file start

---

src/parse-command-line-options.js
src/transformation/commonjs.js
src/transformer.js
test/bin.js
test/parse-command-line-options.js
test/transformation/arrow-functions.js
test/transformation/classes.js
test/transformation/comments.js
test/transformation/default-arguments.js
test/transformation/export-commonjs.js
test/transformation/import-commonjs.js
test/transformation/no-strict.js
test/transformation/object-methods.js
test/transformation/object-shorthands.js
test/transformation/template-string.js

Generalized command line options that deal with enabling/disabling transforms. Removed specific options for Classes and CommonJS transforms, instead accomplishing the same with generic options that can be used to enable/disable any transform.
Simplified the names of all the transform names, and documented them in `--help` output, so one can now actually use them from command line without having to browse the source of Lebab to figure them out.
- Rename `--transformers` option to `--enable`
- Add `--disable` option to disable particular transforms
- Remove `--no-classes` (one can now instead `--disable=class`)
- Remove `--module=commonjs` and enable CommonJS transform by default (if needed one can `--disabe=commonjs`). The two transforms `importCommonjs` and `exportCommonjs` are now …

Improved command line interface

---

.travis.yml
package.json

This makes `npm test` not fail even if `grunt-cli` is not globally installed.

test: add grunt-cli dependency

---

src/transformation/arrow-functions.js
test/transformation/arrow-functions.js

And some additional cleanup of arrow transform.
Solves one of the issues in #90.

Do not transform object methods to arrow functions

---

index.js

Support for Node versions <0.12 was fixed in e6c5a6ae0557fb718b8f2fefb17091b9db411a93, but that was only for when using Lebab in the command line.
This fix adds the same polyfill when Lebab is required as a module.

Fix <0.12 Node support when used as a module

---

.travis.yml
bin/index.js
index.js
package.json
src/parser.js
src/scope/function-hoister.js
src/transform/arg-spread.js
src/transform/arrow.js
src/transform/class/index.js
src/transform/commonjs/export-commonjs.js
src/transform/commonjs/import-commonjs.js
src/transform/default-param/index.js
src/transform/let.js
src/transform/no-strict.js
src/transform/obj-method.js
src/transform/obj-shorthand.js
src/transform/template.js
src/transformer.js
src/traverser.js
test/transform/jsx.js
test/transform/template.js

Using Espree instead of Esprima to parse the code.
Relatively few small fixes were needed to get our tests to pass with Espree.
New branch without the experiments I did in the other one to get the tests working with old NodeJS versions.
Refs: #128

JSX support

---

src/Parser.js
src/traverser.js
test/transform/restSpreadTest.js

Before this, I was getting `SyntaxError: Unexpected token ...` in my React code that uses object rest and spread outside of JSX syntax.
Thankfully, espree supports this with the `experimentalObjectRestSpread` option to the parser (thanks to support for it being required by ESLint).
After parsing successfully, estraverse threw with `Error: Unknown node type ExperimentalRestProperty.`, so I added the node types to the traverse in the same way as the JSX node types.

Add support for object rest and spread operators

---

src/transform/multiVar.js
test/transform/multiVarTest.js

Currently, when multi-var encounters a multi var in a for loop initializer, it throws the error from `multiReplaceStatement` and the process terminates.
This change catches the error, logs the warning and lets it continue with the rest of the file(s).

ignore multi-vars in a for loop initializer

---

src/io.js
test/binTest.js

Cross-platform synchronous reading from stdin.
Based on this [StackOverflow answer](https://stackoverflow.com/a/16048083/5342708).
Re-enabled stdin test on Windows.

Read from stdin on Windows

---

src/withScope.js

I'm not sure what bugs this is causing, but it definitely looks broken. There is no such thing as `scopeManager.upper`. Following the [docs](https://github.com/estools/escope/blob/aa35861faa76a09f01203dee3497a939d70b463c/README.md#example), I changed it to `currentScope.upper`.

Use the correct upper scope

---

src/parseOptions.js
test/parseOptionsTest.js

Sorry for the small change, but this bugged my for some time. Thanks guys, great work!

Fix typo for 'No transforms specifed'

---

src/transform/class/PotentialMethod.js
test/transform/classTest.js

* Fix missing "async" during class transform.
* Add corresponding tests for async.

Fix missing "async" during class transform. (Fixes #220)

---

src/transform/noStrict.js
src/utils/copyComments.js
test/transform/noStrictTest.js

Fixes https://github.com/lebab/lebab/issues/227
I split this into three commits:
1. Adding a test
2. Refactoring copyComments() to allow prepending
3. Fixing the test, using the new copyComments()

`no-strict` transform: preserve preceding comments

---

src/transform/template.js
test/transform/templateTest.js

This fixes https://github.com/lebab/lebab/issues/242 by traversing the
children of a "PlusExpression", so that the transformation gets applied
recursively.

template transform: transform nested concatenation

---

src/Logger.js

Fixes `Cannot read property 'start' of undefined` crash in case there is no `node.loc`, which might happen when using lebab's node API.
Unfortunately I have no good scenario for reproducing the issue. I can just tell you that this may happen in practice when using the node API, thus feeding lebab with already-parsed Babel nodes. I hope you accept the bug fix nevertheless 😉

Make sure warnings cannot cause crash

---

.babelrc
.gitignore
.travis.yml
README.md
package.json
src/Parser.js
src/traverser.js

Mostly updates all dependencies and change/remove some codes/syntax due to the updated modules.
Changes:
- Updates lebab's dependecies and devDependecies
- Uses babel-preset-env instead of babel-preset-2015 as recommended by babeljs.
- Uses ecmaVersion 9 option for espree, and remove experimental rest,spread options since it is now natively supported by espree using ecmaVersion 9.
- Raise minimum node version to 6, since node version 4 is already on EOL.
- Add travis test for node 8,9,10.
- Use `--require babel-register` option on mocha instead of `--compilers js:babel-register` on package.json file
- Update upload-coverage script syntax
- Add new Sublime Plugin ```Lebab ES6 Transform```
Passes all travis tests.

Updates and some changes

---

README.md
src/OptionParser.js
src/builtinTransforms.js
src/transform/arrow.js
src/transform/arrowReturn.js
system-test/binTest.js
test/transform/arrowReturnTest.js
test/transform/arrowTest.js

This is in reference to PR #262 which is basically a limitation of Lebab not handling ```immediate return statements``` of an ```arrow function```
Example:
Lebab does not convert the return statement of the code below
```js
const actionCreator = () => {
return {
type: 'ADD_COUNTER',
payload: { count: 1}
}
}
```
However, the code above is still a valid es6 code, therefor, separating the handling of return statements from the ```arrow``` transform is preferable because it gives the users the freedom to have their return statements preserved (for readability)  or converted (for simplicity)
This PR moves the handling of return statements from the ```arrow``` transform to a separate transform called ```arrow-return```.  Also adds arrowReturnTest and update arrowTest's return statements.
Pros: …

new arrow-return transform

---

src/transform/defaultParam/index.js
test/transform/defaultParamTest.js

This PR adds additional condition which checks if the function's body type is a `BlockStatement` and if not it skips this function. 
Problem: The current logic only checks if a node is a function and assumes that the body type is a `BlockStatement` which is not always the case for an Immediate-return `ArrowFunctionExpression`, since it removes the `{ ... }` and because of that it is no longer considered as a `BlockStatement`, as `BlockStatement` is usually delimited by `{ ... }`
However, this error will not occur if `arrow-return` transform is not used or `default-param` is used before `arrow-return`
Examples: 
```js
// all examples bellow will throw an error
const a = (x) => x; 
const b = () => 1 
const c = () => new Promise()
const d = (y) => [y]
// and so on...
```

Skip default-param for non-BlockStatement body

---

src/transform/class/matchFunctionDeclaration.js
test/transform/classTest.js

Fixes a bug on Lebab where in it throws a `SyntaxError` when `class` transform is enabled and the user is using anonymous function declaration on default export.
example:
```js
export default function() {}
```
- will throw `SyntaxError Cannot read property 'name' of null` when `class` transform is enabled

[class] Prevent lebab from crashing when using anonymous function declaration on default export

---

README.md
src/transform/class/PotentialMethod.js
src/transform/class/index.js
src/transform/class/matchObjectDefinePropertiesCall.js
src/transform/class/matchObjectDefinePropertyCall.js
src/utils/multiReplaceStatement.js
test/transform/classTest.js

This library already supported `defineProperty` and this PR expands that to include `defineProperties`. This is the core request of https://github.com/lebab/lebab/issues/267
`defineProperty` only supported getters and setters and the same is true for `defineProperties`. It could be good to add support for class fields at some point but I focused only on matching the support `defineProperty` already had (and is probably enough for our usecase)
While I was in that code I also expanded support for both `defineProperty` _and_ `defineProperties` to support `static` methods detected based on whether the first argument is `MyClass.prototype` or just `MyClass` as is done in the other class matchers.
For context I've been looking into upgrading a very large library with many prototypal classes to …

Add support for `defineProperties` and static class properties
